-- mysql-replica-init.sql
STOP REPLICA;
CHANGE MASTER TO
  MASTER_HOST='192.168.35.179',
  MASTER_PORT=3306,
  MASTER_USER='replica',
  MASTER_PASSWORD='replica',
  MASTER_AUTO_POSITION = 1;
START REPLICA;