# SPRING_PROFILES_ACTIVE=dev

# 모듈 설정
module:
  price:
    url: https://api.bithumb.com/public/ticker/ALL
    rps: 4
    max-failures: 10
    initial-queue-size: 100
    price-window-size: 10

  trade:
    # read/write 작업 스레드 수
    thread-pool:
      reader: 3
      writer: 2
    # 읽기 재시도 횟수 제한
    reader:
      retry-limit: 3
    # read : num++ , write : num--
    # num = rate-limit, num 을 넘기는 스레드는 잠시 작업을 멈추게 됨.
    rate-limit: 30

  user:
    # 최소 주문 가능 금액
    minimum-order-price: 1000.0
    # 처리된 주문 저장 작업 스레드 수
    thread-pool:
      handler: 1

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crypto
    username: uno
    password: fhzjfelqlqlalfqjsgh

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        # 통계 정보
        generate_statistics: true

        # batch update
        order_updates: true
        jdbc:
          batch_versioned_data: true

# redis
redis:
  # local
#  master:
#      host: localhost
#      port: 6379
#  slaves:
#    - host: localhost
#      port: 6479
  # db server
  master:
    host: 192.168.35.247
    port: 6379
  slaves:
    - host: 192.168.35.247
      port: 6479

# logging
logging:
  level:
    root: error