# SPRING_PROFILES_ACTIVE=dev
price:
  api:
    url: https://api.bithumb.com/public/ticker/ALL
    rps: 4
    max-failures: 10
    initial-queue-size: 100
    price-window-size: 5

server:
  port: 8085
