# @ActiveProfiles("test")
module:
  price:
    url: https://api.bithumb.com/public/ticker/ALL
    rps: 4
    max-failures: 10
    initial-queue-size: 100
    price-window-size: 5

  trade:
    thread-pool:
      reader: 3
      writer: 2
    # 읽기 재시도 횟수 제한
    reader:
      retry-limit: 3
    rate-limit: 20

server:
  port: 8086

redis:
  master:
    host: 192.168.35.247
    port: 6379
  slaves:
    - host: 192.168.35.247
      port: 6479