# SPRING_PROFILES_ACTIVE=dev
price:
  api:
    url: https://api.bithumb.com/public/ticker/ALL
    rps: 4
    max-failures: 10
    initial-queue-size: 100

server:
  port: 8086

redis:
  master:
    host: 192.168.35.247
    port: 6379
  slaves:
    - host: 192.168.35.247
      port: 6479